SELECT
A.ACTIVITY_DESC AS SURVEY,
T.TRIP_ID,
E.FISHING_EVENT_ID AS EVENT_ID,
E.FE_MAJOR_LEVEL_ID AS SET_ID,
YEAR(T.TRIP_START_DATE) AS YEAR,
MONTH(T.TRIP_START_DATE) AS MONTH,
T.TRIP_START_DATE AS DATE,
E.MAJOR_STAT_AREA_CODE,
E.FE_START_LATTITUDE_DEGREE + E.FE_START_LATTITUDE_MINUTE / 60 AS START_LATITUDE,
-(E.FE_START_LONGITUDE_DEGREE + E.FE_START_LONGITUDE_MINUTE / 60) AS START_LONGITUDE,
E.FE_END_LATTITUDE_DEGREE + E.FE_END_LATTITUDE_MINUTE / 60 AS END_LATITUDE,
-(E.FE_END_LONGITUDE_DEGREE + E.FE_END_LONGITUDE_MINUTE / 60) AS END_LONGITUDE,
(IsNull(E.FE_BEGINNING_BOTTOM_DEPTH, E.FE_MIN_BOTTOM_DEPTH) + IsNull(E.FE_END_BOTTOM_DEPTH, E.FE_MAX_BOTTOM_DEPTH))/2  AS DEPTH,
E.FE_BOTTOM_WATER_TEMPERATURE AS TEMPERATURE,
C.CATCH_WEIGHT AS WEIGHT,
C.CATCH_COUNT AS NUMBERS,
C.CATCH_VERIFICATION_CODE,
E.FE_DISTANCE_TRAVELLED AS DISTANCE_FISHED,
G.GEAR_DESC AS GEAR,
S.SPECIES_CODE,
S.SPECIES_SCIENCE_NAME,
S.SPECIES_COMMON_NAME,
V.USABILITY_CODE
FROM GFBioSQL.dbo.TRIP T
    INNER JOIN
    GFBioSQL.dbo.FISHING_EVENT E ON T.TRIP_ID = E.TRIP_ID
    INNER JOIN
    GFBioSQL.dbo.FISHING_EVENT_CATCH CL ON E.FISHING_EVENT_ID = CL.FISHING_EVENT_ID
    INNER JOIN
    GFBioSQL.dbo.CATCH C ON CL.CATCH_ID = C.CATCH_ID
    INNER JOIN
    GFBioSQL.dbo.SPECIES S ON C.SPECIES_CODE = S.SPECIES_CODE
    INNER JOIN
    GFBioSQL.dbo.TRIP_ACTIVITY AS AL ON T.TRIP_ID = AL.TRIP_ID
    INNER JOIN
    GFBioSQL.dbo.ACTIVITY AS A ON AL.ACTIVITY_CODE = A.ACTIVITY_CODE
    INNER JOIN
    GFBioSQL.dbo.GEAR G ON E.GEAR_CODE = G.GEAR_CODE
    INNER JOIN
    GFBioSQL.dbo.Trawl_Specs V ON E.FISHING_EVENT_ID = V.FISHING_EVENT_ID
WHERE E.FE_START_LATTITUDE_DEGREE IS NOT NULL AND E.FE_START_LONGITUDE_DEGREE IS NOT NULL AND A.ACTIVITY_CODE=47
-- insert where here
ORDER BY YEAR, SPECIES_SCIENCE_NAME
