SELECT FE.TRIP_ID, FE.FISHING_EVENT_ID, FE.FE_MAJOR_LEVEL_ID,
   AVG(SDE.SENSOR_DATA_VALUE) AS MEAN_TEMPERATURE, MIN(SDE.SENSOR_DATA_VALUE) AS MIN_TEMPERATURE,
   MAX(SDE.SENSOR_DATA_VALUE) AS MAX_TEMPERATURE , STDEV(SDE.SENSOR_DATA_VALUE) AS SD_TEMPERATURE
FROM GFBioSQL.dbo.FISHING_EVENT FE
   INNER JOIN GFBioSQL.dbo.FISHING_EVENT_SENSOR_DATAFILE FESD ON
   FE.FISHING_EVENT_ID = FESD.FISHING_EVENT_ID
   INNER JOIN GFBioSQL.dbo.SENSOR_DATA SDE ON
   FESD.SENSOR_DATAFILE_NAME = SDE.SENSOR_DATAFILE_NAME
WHERE SENSOR_FILE_COLUMN_NAME = 'temperature' AND
   SDE.TIME_STAMP BETWEEN FE_END_DEPLOYMENT_TIME AND FE_BEGIN_RETRIEVAL_TIME AND
   FE.TRIP_ID IN (82851, 82870, 82872, 82930, 82994, 83010, 83050, 83090, 83411, 83530, 84190, 84270, 84330, 84410, 84431, 84450, 84451)

GROUP BY FE.TRIP_ID, FE_MAJOR_LEVEL_ID, FE.FISHING_EVENT_ID
ORDER BY FE_MAJOR_LEVEL_ID

